### PR TITLE
Add bespoke ORCA periodic and halo boundary condition swaps

### PR DESCRIPTION
**Pull request by twsearle**
## Description

This change follows on from #15 to add support for the `checkerboard` and `equal_region` partitioners of atlas-orca grids. A work-in-progress function to solve this problem was present in `test_orca_mesh.cc` and has been removed now that the full version is available.

This new function to build the remote indices bypasses later changes to the remote indices that would be made during `atlas::mesh::actions::build_parallel_fields`, preserving the setup at the North fold and periodic boundaries of an ORCA grid. These points are an extra halo that is "built-in" to the ORCA grid, that we must account for separately to ordinary atlas halo points.

The solution proposed here uses the `master_global_index` to determine the true master index of any given mesh point, and so its local index. This information is then exchanged with other MPI processes to update the remote indices on every partition.

My understanding is that the reason we can't use the default atlas methods to build parallel fields is that we effectively end up with chains of ghost points (i.e ghost points -> ghost points -> real points). This approach uses the `master_global_index` to uniquely identify each point.

## Impact

This should allow us to run MPI `checkerboard` or `equal_regions` grid partitions whilst recovering the correct behaviour at the ORCA grid boundaries. In particular, the idea is that this will help with memory-bound runs of eORCA12 ocean tasks, where the `serial` partitioner is not appropriate.

## Testing

  * The addition of new tests of each valid partitioner in `test_orca_mesh_boundaries`
  * testing at the Met Office as a component in JOPA

### CODE REVIEW

**Comment by twsearle** [comment]
The testing on ORCA12 grids of this change is looking great - there don't seem to be any issues and it seems like the haloexchange is now doing what it ought to I think.

**Comment by twsearle** [comment]
I thought I ought to add some test plots to make this change clearer.

First I updated the test function so that the vortex data is ~[0,1]. This makes it easier to see where some points still are unfilled with their initial value of 0.

This is what I expect for the ORCA2_T grid:

withfix

withfix_zoomed

This is what happens before the change for the ORCA2_T grid:

withoutfix_zoomed

you can see that a number of points have not been set correctly, one in the top right, and a few more on the boundary for example in this grid. Other grids have similar issues without the fix.

**Comment by wdeconinck** [comment]
Hi @twsearle thank you for this contribution! I will make a review soon.

**Comment by twsearle** [comment]
> Hi @twsearle thank you for this contribution! I will make a review soon.

Thanks, no worries, I just realised this morning I had missed out the update of the partition and the global_index (see my latest commit). Sorry, it didn't cause any issues in the majority of my testing, but I thought it might be responsible for behaviour I am seeing when using gatherScatter.

I have been having a few issues getting builds working in the last few weeks, but as far as I can tell at the moment this change is working on the larger problem sizes as expected.

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/atlas-orca?pullRequest=16) <br/>All committers have signed the CLA.

**Comment by twsearle** [comment]
Hi @wdeconinck I have been looking at the halos again for the orca grid, and I notice that they aren't working. I thought it best in the short-term to add in some logic in this PR to catch when the halo is set and to prevent setting halo > 0.

**Review by wdeconinck — APPROVED** [review]
Thanks @twsearle this is great! It has always been a missing feature.
We need to fix the halo > 0 still in follow-up. Thanks for asserting for now.

**Pull request merged**
